---
title       : Motor Trend Cars Project
subtitle    : Peer Assessment Project
author      : Bhaskar
job         : Evid Learner
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {selfcontained, standalone, draft}
knit        : slidify::knit2slides
---

## Agenda

<br/>
<br/>
<br/>
<br/>

1. Purpose
2. Shiny Application
3. Conclusion

--- .class #id 

## Purpose

<br/>
<br/>
<br/>
<br/>

Consumers are bombarded with many choices when it comes to buying (or leasing) a car.

Which car do we pick ? Choices, choices, choices ???

This Shiny application helps the consumer navigate the complex maze and help make choices.

--- .class #id 

## Shiny Application

<br/>
<br/>

In this project, we leverage the __mtcars__ dataset to:

<br/>

* _Display the summary statistics of the cars based on the type of transmission - automatic or manual_
* _Display a plot to show the relationship between Number of Cylinders (CYL) vs Miles Per Gallon (MPG)_
* _Display a plot to show the relationship between Horsepower (HP) vs Miles Per Gallon (MPG)_
* _Display a table of car reccomendations based on Miles Per Gallon (MPG)_

--- .class #id 

## Conclusion

<br/>
<br/>

Consumers can access the application at [Motor Trend Cars](https://bswamina.shinyapps.io/DDP-Project)

<br/>
<br/>

Hope this application makes it easy for consumers to pick their next car.
